apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deployments-require-labels-and-replica-limit
spec:
  rules:
  - name: deployment-require-label
    match:
      any:
      - resources:
          kinds:
          - Deployment
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            env: staging
  - name: check-for-replica
    match:
      all:
      - resources:
          kinds:
          - Deployment
          - Deployment/scale
          selector:
            matchLabels:
              env: staging
    mutate:
      patchesJson6902: |-
        - path: "/spec/replicas"
          op: add
          value: 2
