apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: <PATH_TO_CERTIFICATE>
    server: <URL:PORT>
  name: bob-kyverno
contexts:
- context:
    cluster: bob-kyverno
    user: bob-kyverno
  name: bob-kyverno
current-context: bob-kyverno
users:
- name: bob-kyverno
  user:
    client-certificate: ./bob.crt
    client-key: ./bob.key
