apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-pod-1
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      hostPort: 80 # disallow-host-ports
    securityContext:
      capabilities:
        add: ["NET_ADMIN"] # disallow-capabilities
      privileged: true # disallow-privileged-containers
  hostPID: true # disallow-host-namespaces
