apiVersion: v1
kind: Secret
metadata:
  name: aks-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    name: aks-cluster
type: Opaque
stringData:
  name: aks-cluster
  server: <Replace with server from step 8>
  config: |
    {
      "bearerToken": "<Replace with token generated in step 12>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<Replace with certificate-authority-data from step 8>"
      }
    }
