apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pods-require-labels
spec:
  rules:
  - name: check-for-pod-label
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            env: staging
